**Numpy is a library of python, works with arrays**

***Functions: ***
1. type: used to know about the variable types
2. dtype: used to find the types of variables
3. size: find the total items number 
4. itemsize: find the byte size 
5. arrange: To make a range (start, end, step) 
6. add: To do addition 
7. shape: To know the dimension (rows, columns) 
8. reshape: To change the dimension (1D, 2D, 3D...)
9. slice: to print a specific portion of values 
10. transpose(T): change rows to columns, and columns to rows

In [1]:
#write a numpy array and print
import numpy as np #np is an alias
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
#Variable and data type

import numpy as np #np is an alias
a = np.array([1,2,3,4,5])
print(type(a)) #type is used to know about the variable types
print(a.dtype) #dtype is used to find the types of variables

<class 'numpy.ndarray'>
int64


In [8]:
#Size: To find how may varables are present in the array
import numpy as np #np is an alias
a = np.array([1,2,3,4,5])
print(a.size)

5


In [17]:
#itemsize: int and float 8 bytes, For complex 16 bytes
import numpy as np #np is an alias
a = np.array([1j+2j])
b = np.array([1,2,3])
print(a.itemsize)
print(b.itemsize)

16
8


In [23]:
#here if values are less than 10, then it will print true. others will be False
import numpy as np #np is an alias
a = np.array([1,2,3,4,5,6,7,8])
print(a<10)

b = np.array([1,2,3,4,5,11,14,15, 10])
print(b==10)

[ True  True  True  True  True  True  True  True]
[False False False False False False False False  True]


In [26]:
#max and min

import numpy as np #np is an alias
a = np.array([1,2,3,4,5,6,7,8])
print("Max is:",a.max())

b = np.array([1,2,3,4,5,11,14,15, 10])
print("Min is:",b.min())

Max is: 8
Min is: 1


In [34]:
#arrange used to set a range of numbers. (Start, end, step)

import numpy as np #np is an alias
a = np.arange(1, 10, 2) #Start = 1, end = 10 and step = 2
print(a)
print(a*2) #will multiply the answer with 2

[1 3 5 7 9]
[ 2  6 10 14 18]


In [48]:
#add: Add a number(2) with all the values in array

import numpy as np #np is an alias
a = np.array([1,2,3])
b = np.add(a,2)
print("Add extra 2 with the values of array :", b)

c = np.array([1,2,3])
d = np.array([4,5,6])
e = np.add(c,d)
print("Add two different array's value :", e)

Add extra 2 with the values of array : [3 4 5]
Add two different array's value : [5 7 9]


In [53]:
#shape: To find the array shape(row, array)

import numpy as np #np is an alias
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.shape)

b = np.array([[[1,2,3],[4,5,6]], [[1,2,3], [4,5,6]]])
print(b.shape)

(3, 3)
(2, 2, 3)


In [63]:
#reshape: To find the array shape(row, array)

import numpy as np #np is an alias
a = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print("2D to 3D:\n", a.reshape(2,2,3))
print("\n2D to 1D:", a.reshape(-1))

2D to 3D:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

2D to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [64]:
#power: to find any number's power (square, cube,...)

import numpy as np #np is an alias
a = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print(a*3)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]
 [30 33 36]]


In [71]:
#rslice: to print some specific numbers from the arrays

import numpy as np #np is an alias
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("1 means index number among arrays and 0: means, print all numbers(0 to end) from the index 1")
print(a[1, 0:]) #1 means index number among arrays and 0: means, print all numbers(0 to end) from the index 1
print("\nprint the last index :")
print(a[-1])
print("\n print all the values from start to end with step 2 :")
print(a[::2])

1 means index number among arrays and 0: means, print all numbers(0 to end) from the index 1
[4 5 6]

print the last index :
[10 11 12]

 print all the values from start to end with step 2 :
[[1 2 3]
 [7 8 9]]


In [73]:
#Transpose: Make row to column, and column to row

import numpy as np #np is an alias
a = np.array([[1,2,3],[4,5,6]])
print(a.T)

[[1 4]
 [2 5]
 [3 6]]
