In [ ]:
import numpy as np

a=np.array([2,4,5,6,7,8,11,3,9])
a

array([ 2,  4,  5,  6,  7,  8, 11,  3,  9])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.size

9

In [ ]:
a.itemsize

8

In [ ]:
a>10

array([False, False, False, False, False, False,  True, False, False])

In [ ]:
a==2

array([ True, False, False, False, False, False, False, False, False])

In [ ]:
a.max()

11

In [ ]:
a.min()

2

In [ ]:
b=np.arange(1,6,2)*2
print(b)

[ 2  6 10]


In [ ]:
d=np.add(b,2)
d

array([ 4,  8, 12])

In [ ]:
c=np.arange(1,6,2)
print(c)

[1 3 5]


In [ ]:
np.add(b,c)

array([ 3,  9, 15])

In [ ]:
print(d)

[ 4  8 12]


In [ ]:
f=np.array([[1,2,3],[4,5,6]])
f.shape

(2, 3)

In [ ]:
g=f.reshape(6)
g

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.power(c,3)

array([  1,  27, 125])

In [ ]:
g[:]

array([1, 2, 3, 4, 5, 6])

In [ ]:
g[2:4:2]

array([3])

In [ ]:
g[::2]

array([1, 3, 5])

In [ ]:
f

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
f[1,0:2]

array([4, 5])

In [ ]:
f.T

array([[1, 4],
       [2, 5],
       [3, 6]])