**Load file from google colab**

In [8]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import numpy as np
x = np.loadtxt('Data.txt')
x = np.array(x)
print(x)

[0. 1. 2. 3.]


In [ ]:
import numpy as np
y = np.arange(5)
np.savetxt('new.txt',y,fmt='%d')

**Load a file from google drive**

In [9]:
import numpy as np

x = np.loadtxt('/content/gdrive/My Drive/Data.txt', dtype=int)
x = np.array(x)
print(x)

# x=np.loadtxt('/content/gdrive/My Drive/grace/data.txt',dtype=int)
# x=np.array(x)
# print(x)

[0 1 2 3]


**What is a Random Number?**
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

In [ ]:
import numpy as np
x = np.random.random((3,4))
print(x)

[[0.09895848 0.51056617 0.12675934 0.10944884]
 [0.12430515 0.07387311 0.45884679 0.32824838]
 [0.39042366 0.79168167 0.28388131 0.73499027]]


**Integers:** The **randint() method** takes a size parameter where you can specify the shape of an array.

In [ ]:
import numpy as np
x = np.random.randint(100, size = (5))
print(x)

[ 3 46 95  3 73]


In [ ]:
import numpy as np
x = np.random.randint(100, size = (3,4))
print(x)

[[97 58  9 30]
 [91 42  5 77]
 [ 6 13 93 77]]


**Floats:** **The rand() method** also allows you to specify the shape of the array.

In [ ]:
import numpy as np
x = np.random.rand(5)
print(x)

[0.38815679 0.15841352 0.787113   0.67466981 0.29685215]


In [ ]:
import numpy as np
x = np.random.rand(3,4)
print(x)

[[0.27854188 0.92691288 0.58800847 0.71139048]
 [0.77941722 0.75800872 0.60510945 0.73726702]
 [0.98701789 0.06223867 0.62896678 0.21678333]]


**Generate Random Number From Array**:
The choice() method takes an array as a parameter and randomly returns one of the values.

The choice() method also allows you to return an array of values.
Add a size parameter to specify the shape of the array.

In [ ]:
import numpy as np
x = np.random.choice([1,2,3,4,5], size = (3,5))
print(x)

[[4 1 2 2 4]
 [4 2 5 3 4]
 [5 3 1 1 4]]


**numpy.zeros**(shape, dtype=float, order='C', *, like=None): 
Return a new array of given shape and type, filled with zeros.

In [ ]:
import numpy as np
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# import numpy as np
# x = np.zeros_like((x))
# print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


**numpy.ones**(shape, dtype=float, order='C', *, like=None): 
Return a new array of given shape and type, filled with ones.

In [ ]:
import numpy as np
x = np.ones((3,4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


**np.empty():** Return a new array of given shape and type, without initializing entries.

In [ ]:
import numpy as np
x = np.empty([2,3], dtype='int')
print(x)

[[94541229193312              0              0]
 [             0              0              0]]


In [ ]:
import numpy as np
x = np.array([1,2,3,4])
print(x.cumprod())
# intermediate results 1, 1*2
# total product 1*2*3 = 6 , 1*2*3*4 = 24

[ 1  2  6 24]


In [ ]:
import numpy as np
x = np.array([1,2,3,4])
print(x.cumsum())
# intermediate results 1, 1+2 = 3
# total product 3+3 = 6 , 6+4 = 10

[ 1  3  6 10]
