In [ ]:
import numpy as np

x=np.loadtxt('data.txt',dtype=int)
x=np.array(x)
print(x)

[0 1 2]


In [ ]:
y=np.arange(5)

np.savetxt('out.txt',y,fmt='%.1f')

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import numpy as np

x=np.loadtxt('/content/gdrive/My Drive/grace/data.txt',dtype=int)
x=np.array(x)
print(x)

[0 1 2]


In [ ]:
y=np.arange(5)

np.savetxt('/content/gdrive/My Drive/grace/out.txt',y,fmt='%.1f')

In [ ]:
for i in x:
  print(i)

0
1
2


In [ ]:
z=np.random.random((4,3))
print(z)

[[0.88878477 0.19795568 0.56549076]
 [0.25882308 0.12001395 0.9112532 ]
 [0.6884278  0.93316371 0.92303235]
 [0.22211947 0.73498041 0.64267442]]


In [ ]:
z=np.random.randint(100)
print(z)

52


In [ ]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
x.cumprod()

NameError: ignored