**What is NumPy?**
NumPy is a Python library used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

**Why Use NumPy?**
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray

**Why is NumPy Faster Than Lists?**
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

**Which Language is NumPy written in?**
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

**Import numpy, use and check version:**

In [ ]:
#import numpy 
#or
import numpy as np #np is called as alias. That means an alternate name for referring to the same thing.

arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
#Version check for numpy
import numpy as np
print(np.__version__)

1.19.5


**Create a NumPy ndarray Object**
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

*We can create a NumPy ndarray object by using the array() function.*

To create an ndarray, we can pass a **list, tuple or any array-like object** into the array() method, and it will be converted into an ndarray:

In [ ]:
import numpy as np
arr = np.array([2,4,7,9]) #List
print(arr)
print(type(arr)) 
print("\n")
arr1 = np.array(('XYZ', 23, 'Green, (1,2,3')) #tuple
print(arr1)
print(type(arr1))
print("\n")
arr2 = np.array({'Apple', 'Rose', 45, 'Apple'}) #set
print(arr2)
print(type(arr2))

[2 4 7 9]
<class 'numpy.ndarray'>


['XYZ' '23' 'Green, (1,2,3']
<class 'numpy.ndarray'>


{'Apple', 'Rose', 45}
<class 'numpy.ndarray'>


**Dimensions in Arrays**

**0-D arrays**, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

**1-D Arrays:** An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

**2-D Arrays:** An array that has 1-D arrays as its elements is called a 2-D array. used to represent matrix or 2nd order tensors. (Matrix operation: numpy.mat)

**3-D arrays:** An array that has 2-D arrays (matrices) as its elements is called 3-D array. used to represent a 3rd order tensor.

**Check Number of Dimensions?:** with ***ndim*** attribute.

In [ ]:
import numpy as np
arr1 = np.array(40) #OD
print('number of dimensions :',arr1.ndim)

arr2 = np.array([1,2,3]) #1D
print('number of dimensions :',arr2.ndim)

arr3 = np.array([[1,2,3],[4,5,6]]) #2D
print('number of dimensions :',arr3.ndim)

arr4 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [1,2,3]]]) #3D
print('number of dimensions :',arr4.ndim)

number of dimensions : 0
number of dimensions : 1
number of dimensions : 2
number of dimensions : 3


**Higher Dimensional Arrays**
An array can have any number of dimensions.

In [ ]:
import numpy as np
arr = np.array([1,2,3], ndmin=5)
print(arr)
print('number of dimensions:', arr.ndim)

[[[[[1 2 3]]]]]
number of dimensions: 5


**NumPy Array Indexing**

**Access Array Elements**
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr[0])
print(arr[1])

1
2


In [ ]:
#Addition between index.
import numpy as np
arr = np.array([1,2,3])
arr1 = arr[1] + arr[2]
print(arr1)

5


**Access 2-D Arrays**
To access elements from 2-D arrays we can use comma separated integers representing the *dimension and the index* of the element.

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[1,2]) #First 1 is the dimension number and 2 is the index number

7


**Access 3-D Arrays**: To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [ ]:
import numpy as np
arr = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]]])
print(arr[0, 1, 3])

arr1 = (arr[0][1][0] + arr[1][1][2])
print('Sum of 5 and 15 is:',arr1)

8
Sum of 5 and 15 is: 20


**Negative Indexing**: Use negative indexing to access an array from the end.

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8]])
print(arr[0, -1])

4


**Slicing arrays**
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].
without defining, start means from 0, end means to the last and step means 1.

In [ ]:
#1D array slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5]) #will print from 1 to 4
print(arr[:5]) #will print 0-4
print(arr[5:]) #will print 5 to end
print(arr[-1]) #will printthe last value
print(arr[1:5:2]) #will print values from 1 to 4 with 2 steps
print(arr[::2]) #will print values from 0-last with 2 steps

[2 3 4 5]
[1 2 3 4 5]
[6 7]
7
[2 4]
[1 3 5 7]


In [ ]:
#2D array slicing
import numpy as np
arr = np.array([[1,2,3,4,5,6,7], [7,6,5,4,3,2,1]])
print(arr[0, 1:5])


[2 3 4 5]


In [ ]:
#3D array slicing
import numpy as np
arr = np.array([[[1,2,3,4], [5,6,7,8]], [[9,10,11,12], [13,14,15,16]]])
print(arr[1, 0, 0:3])

[ 9 10 11]


**Data Types in NumPy**

**i** - integer,
**b** - boolean,
**u** - unsigned integer,
**f** - float,
**c** - complex float,
**m** - timedelta,
**M** - datetime,
**O** - object,
**S** - string,
**U** - unicode string,
**V** - fixed chunk of memory for other type ( void ).

In [ ]:
import numpy as np
arr = np.array([1,2,3])
print(arr.dtype)

arr1 = np.array(['python', 'is', 'fun'])
print(arr1.dtype)

arr2 = np.array([ 1.0 + 2.0j, 1.5 + 2.5j])
print(arr2.dtype)

int64
<U6
complex128


**Creating Arrays With a Defined Data Type**: 
For i, u, f, S and U we can define size as well.

In [ ]:
import numpy as np
arr = np.array([1,2,3], dtype= 'S4')
print(arr.dtype)

|S4


**Converting Data Type on Existing Arrays:** The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [ ]:
#Normal way

import numpy as np
arr = np.array([1.1,2.1,3.1], dtype= 'i')
print(arr)
print(arr.dtype)

[1 2 3]
int32


In [ ]:
#using astype
import numpy as np
arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#Change data type from float to integer by using int as parameter value:

#using astype
import numpy as np
arr = np.array([0 ,2.1,3.1])

newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[False  True  True]
bool


**NumPy Array Copy vs View:**
The Difference Between Copy and View:

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [ ]:
#copy
import numpy as np
arr = np.array([1,2,3])
a = arr.copy()

print('arr is:',arr)
print('a is:',a)

#if wq change the values of arr or a, it will not change the values for others.

arr[0] = 40 #change the value of ar's first index
print("a will not be affected:",arr)

arr is: [1 2 3]
a is: [1 2 3]
a will not be affected: [40  2  3]


In [ ]:
#view
import numpy as np
arr = np.array([1,2,3,4])
x = arr.view()

print("arr is:",arr)
print("x is:", x)

#if we change the value of arr or x, it will change the others value also.
arr[1] = 40 #change the 1st index of arr.
print("arr after changing value:",arr)
print("x after changing arr:", x)

arr is: [1 2 3 4]
x is: [1 2 3 4]
arr after changing value: [ 1 40  3  4]
x after changing arr: [ 1 40  3  4]


**Check if Array Owns it's Data**

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute ***base*** that returns ***None*** if the array owns the data.

In [ ]:
#view
import numpy as np
arr = np.array([1,2,3,4])
x = arr.view()
y = arr.copy()

print("arr is:",arr)
print("x is:", x)
print("y is:", y)

#Find Base
print("\narr base is:", arr.base) #will be none. cause carries original values
print("x base is:", x.base) #will not be none. cause does not carry original values. It will be affected by changing the orginal values
print("y base is:", y.base) #will be none. cause carries original values

arr is: [1 2 3 4]
x is: [1 2 3 4]
y is: [1 2 3 4]

arr base is: None
x base is: [1 2 3 4]
y base is: None


**Shape of an Array**
The shape of an array is the number of elements in each dimension. (Total number of Rows, coulumns)

In [ ]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6]])
print(arr.shape)

(2, 3)


In [ ]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [3,4,5]]])
print(arr.shape)

(2, 2, 3)


Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

In [ ]:
import numpy as np
arr = np.array([1,2,3,4], ndmin=5)

print(arr)
print("Shape of array",arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array (1, 1, 1, 1, 4)


**Reshaping arrays**
Reshaping means changing the shape of an array.

In [ ]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [3,4,5]]])
print(arr.shape)

Reshape From 1-D to 2-D

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr1 = arr.reshape(3,2)
print(arr1)
print(arr1.base) #check 1rr1 is copy or view. it will be a view

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


Reshape From 1-D to 3-D

If a dimesion is unknown. then just pass -1 as the value, and NumPy will calculate this number for you.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(3,2,2)) 
print("\nReshape with -1:\n",arr.reshape(3,2,-1))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Reshape with -1:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Flattening the arrays: 
Any dimesion to 1D

In [ ]:
import numpy as np
arr = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [3,4,5]]])
print("With flatten", arr.flatten())

#we can do it also with reshape[-1]
arr1 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [3,4,5]]])
print("With reshape",arr1.reshape(-1))

With flatten [1 2 3 4 5 6 1 2 3 3 4 5]
With reshape [1 2 3 4 5 6 1 2 3 3 4 5]


**Iterating Arrays**
Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

**Iterating Arrays Using nditer()**

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

If we iterate on a 1-D array it will go through each element one by one.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
for elements in arr:
  print(elements, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

2D array

In [ ]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
for elements in arr2:
  print(elements)

for values in arr2:
  for all_values in values:
    print(all_values, end = " ")

[1 2 3]
[4 5 6]
1 2 3 4 5 6 

In [ ]:
import numpy as np
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
for elements in np.nditer(arr2):
  print(elements, end = " ")

1 2 3 4 5 6 

3D Array

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for elements in arr:
  print(elements)

arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr1:
  for y in x:
    for z in y:
      print(z, end = " ")

for values in np.nditer(arr):
  print(values, end=" ")

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1 2 3 4 5 6 7 8 9 10 11 12 1 2 3 4 5 6 7 8 9 10 11 12 

**Iterating Array With Different Data Types**
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

***NumPy does not change the data type of the element*** in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].
In result, b is the extra space.

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for elements in np.nditer(arr, flags = ['buffered'], op_dtypes=['S']):
  print(elements, end=" ")

b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9' b'10' b'11' b'12' 

Iterating With Different Step Size

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for elements in np.nditer(arr[0, 1, ::2]):
  print(elements, end=" ")

4 6 

Enumerated Iteration Using ndenumerate(): To print the values along with index number

In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for index,elements in np.ndenumerate(arr):
  print(index, elements)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


**Joining NumPy Arrays**
Joining means putting contents of two or more arrays in a single array. By using concatenate() function.

In [1]:
#1D Array
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [5]:
#2D Array
import numpy as np

arr1 = np.array([[1, 2], [3,4]])

arr2 = np.array([[5,6], [7,8]])

arr = np.concatenate((arr1, arr2), axis = 1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
#2D Array
import numpy as np

arr1 = np.array([[[1, 2], [3,4]], [[1, 2], [3,4]]])

arr2 = np.array([[[5,6], [7,8]], [[1, 2], [3,4]]])

arr = np.concatenate((arr1, arr2), axis = 2)

print(arr)

[[[1 2 5 6]
  [3 4 7 8]]

 [[1 2 1 2]
  [3 4 3 4]]]


**Joining Arrays Using Stack Functions**
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [12]:
#2D Array
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.stack((arr1, arr2), axis = 1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
#Stack in rows

#2D Array
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [16]:
#Stack in columns

#2D Array
import numpy as np

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#dstack(): NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

**Addition between array**

In [18]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.add(arr1, arr2)

print(arr)

[5 7 9]
